/*
 * ex: set ro:
 * DO NOT EDIT.
 * generated by smc (http://smc.sourceforge.net/)
 * from file : AppClass.sm
 */

#ifndef _H_APPCLASS_SM
#define _H_APPCLASS_SM

#include <assert.h>
#define STATEMAP_DEBUG 1
#include <statemap.h>


struct AppClass;
struct AppClassContext;

struct AppClassState
{

    void(*EOS)(struct AppClassContext*);
    void(*One)(struct AppClassContext*);
    void(*Unknown)(struct AppClassContext*);
    void(*Zero)(struct AppClassContext*);

    void(*Default)(struct AppClassContext*);
    STATE_MEMBERS
};

extern const struct AppClassState Map1_Start;
extern const struct AppClassState Map1_Zeros;
extern const struct AppClassState Map1_Ones;
extern const struct AppClassState Map1_OK;
extern const struct AppClassState Map1_Error;

struct AppClassContext
{
    struct AppClass *_owner;
    FSM_MEMBERS(AppClass)
};

#define AppClassContext_Init(fsm, owner) \
    FSM_INIT((fsm), &Map1_Start); \
    (fsm)->_owner = (owner);

#define AppClassContext_EOS(fsm) \
    assert(getState(fsm) != NULL); \
    setTransition((fsm), "EOS"); \
    getState(fsm)->EOS(fsm); \
    setTransition((fsm), NULL);

#define AppClassContext_One(fsm) \
    assert(getState(fsm) != NULL); \
    setTransition((fsm), "One"); \
    getState(fsm)->One(fsm); \
    setTransition((fsm), NULL);

#define AppClassContext_Unknown(fsm) \
    assert(getState(fsm) != NULL); \
    setTransition((fsm), "Unknown"); \
    getState(fsm)->Unknown(fsm); \
    setTransition((fsm), NULL);

#define AppClassContext_Zero(fsm) \
    assert(getState(fsm) != NULL); \
    setTransition((fsm), "Zero"); \
    getState(fsm)->Zero(fsm); \
    setTransition((fsm), NULL);

#endif

/*
 * Local variables:
 *  buffer-read-only: t
 * End:
 */
