/*
 * ex: set ro:
 * DO NOT EDIT.
 * generated by smc (http://smc.sourceforge.net/)
 * from file : stoplight.sm
 */

#ifndef _H_STOPLIGHT_SM
#define _H_STOPLIGHT_SM

#include <assert.h>
#define STATEMAP_DEBUG 1
#include <statemap.h>


struct smc_ex4_Stoplight;
struct smc_ex4_stoplightContext;

struct smc_ex4_StoplightState
{

    void(*Timeout)(struct smc_ex4_stoplightContext*);

    void(*Default)(struct smc_ex4_stoplightContext*);
    STATE_MEMBERS
};

extern const struct smc_ex4_StoplightState smc_ex4_StopMap_EastWestGreen;
extern const struct smc_ex4_StoplightState smc_ex4_StopMap_EastWestYellow;
extern const struct smc_ex4_StoplightState smc_ex4_StopMap_NorthSouthGreen;
extern const struct smc_ex4_StoplightState smc_ex4_StopMap_NorthSouthYellow;

struct smc_ex4_stoplightContext
{
    struct smc_ex4_Stoplight *_owner;
    FSM_MEMBERS(smc_ex4_Stoplight)
};

#define smc_ex4_stoplightContext_Init(fsm, owner) \
    FSM_INIT((fsm), &smc_ex4_StopMap_NorthSouthGreen); \
    (fsm)->_owner = (owner);

#define smc_ex4_stoplightContext_Timeout(fsm) \
    assert(getState(fsm) != NULL); \
    setTransition((fsm), "Timeout"); \
    getState(fsm)->Timeout(fsm); \
    setTransition((fsm), NULL);

#endif

/*
 * Local variables:
 *  buffer-read-only: t
 * End:
 */
