/*
 * ex: set ro:
 * DO NOT EDIT.
 * generated by smc (http://smc.sourceforge.net/)
 * from file : stoplight.sm
 */


extern int YellowTimer;
extern int NSGreenTimer;
extern int EWGreenTimer;


#include "stoplight.h"
#include "stoplight_sm.h"

#define getOwner(fsm) \
    (fsm)->_owner

#define POPULATE_STATE(state) \
    state##_Timeout, \
    state##_Default

#define ENTRY_STATE(state)

#define EXIT_STATE(state)

static void smc_ex4_StoplightState_Timeout(struct smc_ex4_stoplightContext *fsm)
{
    getState(fsm)->Default(fsm);
}

static void smc_ex4_StoplightState_Default(struct smc_ex4_stoplightContext *fsm)
{
    if (getDebugFlag(fsm) != 0) {
        TRACE("TRANSITION   : %s.%s\n", getName(getState(fsm)), getTransition(fsm));
    }
    State_Default(fsm);
}

#define smc_ex4_StopMap_EastWestGreen_Timeout smc_ex4_StoplightState_Timeout
#define smc_ex4_StopMap_EastWestGreen_Default smc_ex4_StoplightState_Default
#define smc_ex4_StopMap_EastWestGreen_Entry NULL
#define smc_ex4_StopMap_EastWestGreen_Exit NULL
#define smc_ex4_StopMap_EastWestYellow_Timeout smc_ex4_StoplightState_Timeout
#define smc_ex4_StopMap_EastWestYellow_Default smc_ex4_StoplightState_Default
#define smc_ex4_StopMap_EastWestYellow_Entry NULL
#define smc_ex4_StopMap_EastWestYellow_Exit NULL
#define smc_ex4_StopMap_NorthSouthGreen_Timeout smc_ex4_StoplightState_Timeout
#define smc_ex4_StopMap_NorthSouthGreen_Default smc_ex4_StoplightState_Default
#define smc_ex4_StopMap_NorthSouthGreen_Entry NULL
#define smc_ex4_StopMap_NorthSouthGreen_Exit NULL
#define smc_ex4_StopMap_NorthSouthYellow_Timeout smc_ex4_StoplightState_Timeout
#define smc_ex4_StopMap_NorthSouthYellow_Default smc_ex4_StoplightState_Default
#define smc_ex4_StopMap_NorthSouthYellow_Entry NULL
#define smc_ex4_StopMap_NorthSouthYellow_Exit NULL
#define smc_ex4_StopMap_DefaultState_Timeout smc_ex4_StoplightState_Timeout

#undef smc_ex4_StopMap_EastWestGreen_Timeout
static void smc_ex4_StopMap_EastWestGreen_Timeout(struct smc_ex4_stoplightContext *fsm)
{
    struct smc_ex4_Stoplight* ctxt = getOwner(fsm);

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : smc_ex4_StopMap_EastWestGreen)\n");
    }
    EXIT_STATE(getState(fsm));
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: smc_ex4_StopMap_&smc_ex4_StopMap_EastWestGreen.Timeout()\n");
    }
    clearState(fsm);
    smc_ex4_Stoplight_TurnLight(ctxt, EWLIGHT, YELLOW);
    smc_ex4_Stoplight_SetTimer(ctxt, YellowTimer);
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : smc_ex4_StopMap_&smc_ex4_StopMap_EastWestGreen.Timeout()\n");
    }
    setState(fsm, &smc_ex4_StopMap_EastWestYellow);
    ENTRY_STATE(getState(fsm));
}

const struct smc_ex4_StoplightState smc_ex4_StopMap_EastWestGreen = { POPULATE_STATE(smc_ex4_StopMap_EastWestGreen), 0, "smc_ex4_StopMap_EastWestGreen" };

#undef smc_ex4_StopMap_EastWestYellow_Timeout
static void smc_ex4_StopMap_EastWestYellow_Timeout(struct smc_ex4_stoplightContext *fsm)
{
    struct smc_ex4_Stoplight* ctxt = getOwner(fsm);

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : smc_ex4_StopMap_EastWestYellow)\n");
    }
    EXIT_STATE(getState(fsm));
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: smc_ex4_StopMap_&smc_ex4_StopMap_EastWestYellow.Timeout()\n");
    }
    clearState(fsm);
    smc_ex4_Stoplight_TurnLight(ctxt, EWLIGHT, RED);
    smc_ex4_Stoplight_TurnLight(ctxt, NSLIGHT, GREEN);
    smc_ex4_Stoplight_SetTimer(ctxt, NSGreenTimer);
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : smc_ex4_StopMap_&smc_ex4_StopMap_EastWestYellow.Timeout()\n");
    }
    setState(fsm, &smc_ex4_StopMap_NorthSouthGreen);
    ENTRY_STATE(getState(fsm));
}

const struct smc_ex4_StoplightState smc_ex4_StopMap_EastWestYellow = { POPULATE_STATE(smc_ex4_StopMap_EastWestYellow), 1, "smc_ex4_StopMap_EastWestYellow" };

#undef smc_ex4_StopMap_NorthSouthGreen_Timeout
static void smc_ex4_StopMap_NorthSouthGreen_Timeout(struct smc_ex4_stoplightContext *fsm)
{
    struct smc_ex4_Stoplight* ctxt = getOwner(fsm);

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : smc_ex4_StopMap_NorthSouthGreen)\n");
    }
    EXIT_STATE(getState(fsm));
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: smc_ex4_StopMap_&smc_ex4_StopMap_NorthSouthGreen.Timeout()\n");
    }
    clearState(fsm);
    smc_ex4_Stoplight_TurnLight(ctxt, NSLIGHT, YELLOW);
    smc_ex4_Stoplight_SetTimer(ctxt, YellowTimer);
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : smc_ex4_StopMap_&smc_ex4_StopMap_NorthSouthGreen.Timeout()\n");
    }
    setState(fsm, &smc_ex4_StopMap_NorthSouthYellow);
    ENTRY_STATE(getState(fsm));
}

const struct smc_ex4_StoplightState smc_ex4_StopMap_NorthSouthGreen = { POPULATE_STATE(smc_ex4_StopMap_NorthSouthGreen), 2, "smc_ex4_StopMap_NorthSouthGreen" };

#undef smc_ex4_StopMap_NorthSouthYellow_Timeout
static void smc_ex4_StopMap_NorthSouthYellow_Timeout(struct smc_ex4_stoplightContext *fsm)
{
    struct smc_ex4_Stoplight* ctxt = getOwner(fsm);

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : smc_ex4_StopMap_NorthSouthYellow)\n");
    }
    EXIT_STATE(getState(fsm));
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: smc_ex4_StopMap_&smc_ex4_StopMap_NorthSouthYellow.Timeout()\n");
    }
    clearState(fsm);
    smc_ex4_Stoplight_TurnLight(ctxt, NSLIGHT, RED);
    smc_ex4_Stoplight_TurnLight(ctxt, EWLIGHT, GREEN);
    smc_ex4_Stoplight_SetTimer(ctxt, EWGreenTimer);
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : smc_ex4_StopMap_&smc_ex4_StopMap_NorthSouthYellow.Timeout()\n");
    }
    setState(fsm, &smc_ex4_StopMap_EastWestGreen);
    ENTRY_STATE(getState(fsm));
}

const struct smc_ex4_StoplightState smc_ex4_StopMap_NorthSouthYellow = { POPULATE_STATE(smc_ex4_StopMap_NorthSouthYellow), 3, "smc_ex4_StopMap_NorthSouthYellow" };

/*
 * Local variables:
 *  buffer-read-only: t
 * End:
 */
