/*
 * ex: set ro:
 * DO NOT EDIT.
 * generated by smc (http://smc.sourceforge.net/)
 * from file : AppClass.sm
 */

#include "AppClass.h"
#include "AppClass_sm.h"

#define getOwner(fsm) \
    (fsm)->_owner

#define POPULATE_STATE(state) \
    state##_C, \
    state##_EOS, \
    state##_Error, \
    state##_OK, \
    state##_One, \
    state##_Unknown, \
    state##_Zero, \
    state##_Default

#define ENTRY_STATE(state)

#define EXIT_STATE(state)

static void AppClassState_C(struct AppClassContext *fsm)
{
    getState(fsm)->Default(fsm);
}

static void AppClassState_EOS(struct AppClassContext *fsm)
{
    getState(fsm)->Default(fsm);
}

static void AppClassState_Error(struct AppClassContext *fsm)
{
    getState(fsm)->Default(fsm);
}

static void AppClassState_OK(struct AppClassContext *fsm)
{
    getState(fsm)->Default(fsm);
}

static void AppClassState_One(struct AppClassContext *fsm)
{
    getState(fsm)->Default(fsm);
}

static void AppClassState_Unknown(struct AppClassContext *fsm)
{
    getState(fsm)->Default(fsm);
}

static void AppClassState_Zero(struct AppClassContext *fsm)
{
    getState(fsm)->Default(fsm);
}

static void AppClassState_Default(struct AppClassContext *fsm)
{
    if (getDebugFlag(fsm) != 0) {
        TRACE("TRANSITION   : %s.%s\n", getName(getState(fsm)), getTransition(fsm));
    }
    State_Default(fsm);
}

#define StartMap_PushIt_C AppClassState_C
#define StartMap_PushIt_EOS AppClassState_EOS
#define StartMap_PushIt_Error AppClassState_Error
#define StartMap_PushIt_OK AppClassState_OK
#define StartMap_PushIt_One AppClassState_One
#define StartMap_PushIt_Unknown AppClassState_Unknown
#define StartMap_PushIt_Zero AppClassState_Zero
#define StartMap_PushIt_Default AppClassState_Default
#define StartMap_PushIt_Entry NULL
#define StartMap_PushIt_Exit NULL
#define StartMap_PopIt_C AppClassState_C
#define StartMap_PopIt_EOS AppClassState_EOS
#define StartMap_PopIt_Error AppClassState_Error
#define StartMap_PopIt_OK AppClassState_OK
#define StartMap_PopIt_One AppClassState_One
#define StartMap_PopIt_Unknown AppClassState_Unknown
#define StartMap_PopIt_Zero AppClassState_Zero
#define StartMap_PopIt_Default AppClassState_Default
#define StartMap_PopIt_Entry NULL
#define StartMap_PopIt_Exit NULL
#define StartMap_Acceptable_C AppClassState_C
#define StartMap_Acceptable_EOS AppClassState_EOS
#define StartMap_Acceptable_Error AppClassState_Error
#define StartMap_Acceptable_OK AppClassState_OK
#define StartMap_Acceptable_One AppClassState_One
#define StartMap_Acceptable_Unknown AppClassState_Unknown
#define StartMap_Acceptable_Zero AppClassState_Zero
#define StartMap_Acceptable_Default AppClassState_Default
#define StartMap_Acceptable_Entry NULL
#define StartMap_Acceptable_Exit NULL
#define StartMap_Unacceptable_C AppClassState_C
#define StartMap_Unacceptable_EOS AppClassState_EOS
#define StartMap_Unacceptable_Error AppClassState_Error
#define StartMap_Unacceptable_OK AppClassState_OK
#define StartMap_Unacceptable_One AppClassState_One
#define StartMap_Unacceptable_Unknown AppClassState_Unknown
#define StartMap_Unacceptable_Zero AppClassState_Zero
#define StartMap_Unacceptable_Default AppClassState_Default
#define StartMap_Unacceptable_Entry NULL
#define StartMap_Unacceptable_Exit NULL
#define StartMap_DefaultState_C AppClassState_C
#define StartMap_DefaultState_EOS AppClassState_EOS
#define StartMap_DefaultState_Error AppClassState_Error
#define StartMap_DefaultState_OK AppClassState_OK
#define StartMap_DefaultState_One AppClassState_One
#define StartMap_DefaultState_Unknown AppClassState_Unknown
#define StartMap_DefaultState_Zero AppClassState_Zero

#undef StartMap_PushIt_EOS
#define StartMap_PushIt_EOS StartMap_DefaultState_EOS
#undef StartMap_PopIt_EOS
#define StartMap_PopIt_EOS StartMap_DefaultState_EOS
#undef StartMap_Acceptable_EOS
#define StartMap_Acceptable_EOS StartMap_DefaultState_EOS
#undef StartMap_Unacceptable_EOS
#define StartMap_Unacceptable_EOS StartMap_DefaultState_EOS
#undef StartMap_DefaultState_EOS
static void StartMap_DefaultState_EOS(struct AppClassContext *fsm)
{
    struct AppClass* ctxt = getOwner(fsm);

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : StartMap_DefaultState)\n");
    }
    EXIT_STATE(getState(fsm));
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: StartMap_&StartMap_DefaultState.EOS()\n");
    }
    clearState(fsm);
    AppClass_Unacceptable(ctxt);
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : StartMap_&StartMap_DefaultState.EOS()\n");
    }
    setState(fsm, &StartMap_Unacceptable);
    ENTRY_STATE(getState(fsm));
}

#undef StartMap_PushIt_Unknown
#define StartMap_PushIt_Unknown StartMap_DefaultState_Unknown
#undef StartMap_PopIt_Unknown
#define StartMap_PopIt_Unknown StartMap_DefaultState_Unknown
#undef StartMap_Acceptable_Unknown
#define StartMap_Acceptable_Unknown StartMap_DefaultState_Unknown
#undef StartMap_Unacceptable_Unknown
#define StartMap_Unacceptable_Unknown StartMap_DefaultState_Unknown
#undef StartMap_DefaultState_Unknown
static void StartMap_DefaultState_Unknown(struct AppClassContext *fsm)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : StartMap_DefaultState)\n");
    }
    EXIT_STATE(getState(fsm));
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: StartMap_&StartMap_DefaultState.Unknown()\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : StartMap_&StartMap_DefaultState.Unknown()\n");
    }
    setState(fsm, &StartMap_Unacceptable);
    ENTRY_STATE(getState(fsm));
}

#undef StartMap_PushIt_C
static void StartMap_PushIt_C(struct AppClassContext *fsm)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : StartMap_PushIt)\n");
    }
    EXIT_STATE(getState(fsm));
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: StartMap_&StartMap_PushIt.C()\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : StartMap_&StartMap_PushIt.C()\n");
    }
    setState(fsm, &StartMap_PopIt);
    ENTRY_STATE(getState(fsm));
}

#undef StartMap_PushIt_Error
static void StartMap_PushIt_Error(struct AppClassContext *fsm)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : StartMap_PushIt)\n");
    }
    EXIT_STATE(getState(fsm));
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: StartMap_&StartMap_PushIt.Error()\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : StartMap_&StartMap_PushIt.Error()\n");
    }
    setState(fsm, &StartMap_Unacceptable);
    ENTRY_STATE(getState(fsm));
}

#undef StartMap_PushIt_OK
static void StartMap_PushIt_OK(struct AppClassContext *fsm)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : StartMap_PushIt)\n");
    }
    EXIT_STATE(getState(fsm));
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: StartMap_&StartMap_PushIt.OK()\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : StartMap_&StartMap_PushIt.OK()\n");
    }
    setState(fsm, &StartMap_PopIt);
    ENTRY_STATE(getState(fsm));
}

#undef StartMap_PushIt_One
static void StartMap_PushIt_One(struct AppClassContext *fsm)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : StartMap_PushIt)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: StartMap_&StartMap_PushIt.One()\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : StartMap_&StartMap_PushIt.One()\n");
    }
    pushState(fsm, &OnesMap_PushIt);
    ENTRY_STATE(getState(fsm));
}

#undef StartMap_PushIt_Zero
static void StartMap_PushIt_Zero(struct AppClassContext *fsm)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : StartMap_PushIt)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: StartMap_&StartMap_PushIt.Zero()\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : StartMap_&StartMap_PushIt.Zero()\n");
    }
    pushState(fsm, &ZerosMap_PushIt);
    ENTRY_STATE(getState(fsm));
}

const struct AppClassState StartMap_PushIt = { POPULATE_STATE(StartMap_PushIt), 0, "StartMap_PushIt" };

#undef StartMap_PopIt_Default
static void StartMap_PopIt_Default(struct AppClassContext *fsm)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : StartMap_PopIt)\n");
    }
    EXIT_STATE(getState(fsm));
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: StartMap_&StartMap_PopIt.Default()\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : StartMap_&StartMap_PopIt.Default()\n");
    }
    setState(fsm, &StartMap_Unacceptable);
    ENTRY_STATE(getState(fsm));
}

#undef StartMap_PopIt_EOS
static void StartMap_PopIt_EOS(struct AppClassContext *fsm)
{
    struct AppClass* ctxt = getOwner(fsm);

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : StartMap_PopIt)\n");
    }
    EXIT_STATE(getState(fsm));
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: StartMap_&StartMap_PopIt.EOS()\n");
    }
    clearState(fsm);
    AppClass_Acceptable(ctxt);
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : StartMap_&StartMap_PopIt.EOS()\n");
    }
    setState(fsm, &StartMap_Acceptable);
    ENTRY_STATE(getState(fsm));
}

const struct AppClassState StartMap_PopIt = { POPULATE_STATE(StartMap_PopIt), 1, "StartMap_PopIt" };

const struct AppClassState StartMap_Acceptable = { POPULATE_STATE(StartMap_Acceptable), 2, "StartMap_Acceptable" };

#undef StartMap_Unacceptable_Default
static void StartMap_Unacceptable_Default(struct AppClassContext *fsm)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : StartMap_Unacceptable)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: StartMap_&StartMap_Unacceptable.Default()\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : StartMap_&StartMap_Unacceptable.Default()\n");
    }
}

const struct AppClassState StartMap_Unacceptable = { POPULATE_STATE(StartMap_Unacceptable), 3, "StartMap_Unacceptable" };

#define ZerosMap_PushIt_C AppClassState_C
#define ZerosMap_PushIt_EOS AppClassState_EOS
#define ZerosMap_PushIt_Error AppClassState_Error
#define ZerosMap_PushIt_OK AppClassState_OK
#define ZerosMap_PushIt_One AppClassState_One
#define ZerosMap_PushIt_Unknown AppClassState_Unknown
#define ZerosMap_PushIt_Zero AppClassState_Zero
#define ZerosMap_PushIt_Default AppClassState_Default
#define ZerosMap_PushIt_Entry NULL
#define ZerosMap_PushIt_Exit NULL
#define ZerosMap_PopIt_C AppClassState_C
#define ZerosMap_PopIt_EOS AppClassState_EOS
#define ZerosMap_PopIt_Error AppClassState_Error
#define ZerosMap_PopIt_OK AppClassState_OK
#define ZerosMap_PopIt_One AppClassState_One
#define ZerosMap_PopIt_Unknown AppClassState_Unknown
#define ZerosMap_PopIt_Zero AppClassState_Zero
#define ZerosMap_PopIt_Default AppClassState_Default
#define ZerosMap_PopIt_Entry NULL
#define ZerosMap_PopIt_Exit NULL
#define ZerosMap_DefaultState_C AppClassState_C
#define ZerosMap_DefaultState_EOS AppClassState_EOS
#define ZerosMap_DefaultState_Error AppClassState_Error
#define ZerosMap_DefaultState_OK AppClassState_OK
#define ZerosMap_DefaultState_One AppClassState_One
#define ZerosMap_DefaultState_Unknown AppClassState_Unknown
#define ZerosMap_DefaultState_Zero AppClassState_Zero

#undef ZerosMap_PushIt_EOS
#define ZerosMap_PushIt_EOS ZerosMap_DefaultState_EOS
#undef ZerosMap_PopIt_EOS
#define ZerosMap_PopIt_EOS ZerosMap_DefaultState_EOS
#undef ZerosMap_DefaultState_EOS
static void ZerosMap_DefaultState_EOS(struct AppClassContext *fsm)
{
    struct AppClass* ctxt = getOwner(fsm);

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : ZerosMap_DefaultState)\n");
    }
    EXIT_STATE(getState(fsm));
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: ZerosMap_&ZerosMap_DefaultState.EOS()\n");
    }
    clearState(fsm);
    emptyStateStack(fsm);
    AppClass_Unacceptable(ctxt);
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : ZerosMap_&ZerosMap_DefaultState.EOS()\n");
    }
    setState(fsm, &StartMap_Unacceptable);
    ENTRY_STATE(getState(fsm));
}

#undef ZerosMap_PushIt_Unknown
#define ZerosMap_PushIt_Unknown ZerosMap_DefaultState_Unknown
#undef ZerosMap_PopIt_Unknown
#define ZerosMap_PopIt_Unknown ZerosMap_DefaultState_Unknown
#undef ZerosMap_DefaultState_Unknown
static void ZerosMap_DefaultState_Unknown(struct AppClassContext *fsm)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : ZerosMap_DefaultState)\n");
    }
    EXIT_STATE(getState(fsm));
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: ZerosMap_&ZerosMap_DefaultState.Unknown()\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : ZerosMap_&ZerosMap_DefaultState.Unknown()\n");
    }
    setState(fsm, &StartMap_Unacceptable);
    ENTRY_STATE(getState(fsm));
}

#undef ZerosMap_PushIt_C
static void ZerosMap_PushIt_C(struct AppClassContext *fsm)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : ZerosMap_PushIt)\n");
    }
    EXIT_STATE(getState(fsm));
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: ZerosMap_&ZerosMap_PushIt.C()\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : ZerosMap_&ZerosMap_PushIt.C()\n");
    }
    setState(fsm, &ZerosMap_PopIt);
    ENTRY_STATE(getState(fsm));
}

#undef ZerosMap_PushIt_Error
static void ZerosMap_PushIt_Error(struct AppClassContext *fsm)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : ZerosMap_PushIt)\n");
    }
    EXIT_STATE(getState(fsm));
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: ZerosMap_&ZerosMap_PushIt.Error()\n");
    }
    clearState(fsm);
    emptyStateStack(fsm);
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : ZerosMap_&ZerosMap_PushIt.Error()\n");
    }
    setState(fsm, &StartMap_Unacceptable);
    ENTRY_STATE(getState(fsm));
}

#undef ZerosMap_PushIt_OK
static void ZerosMap_PushIt_OK(struct AppClassContext *fsm)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : ZerosMap_PushIt)\n");
    }
    EXIT_STATE(getState(fsm));
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: ZerosMap_&ZerosMap_PushIt.OK()\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : ZerosMap_&ZerosMap_PushIt.OK()\n");
    }
    setState(fsm, &ZerosMap_PopIt);
    ENTRY_STATE(getState(fsm));
}

#undef ZerosMap_PushIt_One
static void ZerosMap_PushIt_One(struct AppClassContext *fsm)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : ZerosMap_PushIt)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: ZerosMap_&ZerosMap_PushIt.One()\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : ZerosMap_&ZerosMap_PushIt.One()\n");
    }
    pushState(fsm, &OnesMap_PushIt);
    ENTRY_STATE(getState(fsm));
}

#undef ZerosMap_PushIt_Zero
static void ZerosMap_PushIt_Zero(struct AppClassContext *fsm)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : ZerosMap_PushIt)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: ZerosMap_&ZerosMap_PushIt.Zero()\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : ZerosMap_&ZerosMap_PushIt.Zero()\n");
    }
    pushState(fsm, &ZerosMap_PushIt);
    ENTRY_STATE(getState(fsm));
}

const struct AppClassState ZerosMap_PushIt = { POPULATE_STATE(ZerosMap_PushIt), 0, "ZerosMap_PushIt" };

#undef ZerosMap_PopIt_Default
static void ZerosMap_PopIt_Default(struct AppClassContext *fsm)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : ZerosMap_PopIt)\n");
    }
    EXIT_STATE(getState(fsm));
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: ZerosMap_&ZerosMap_PopIt.Default()\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : ZerosMap_&ZerosMap_PopIt.Default()\n");
    }
    popState(fsm);
    AppClassContext_Error(fsm);
}

#undef ZerosMap_PopIt_Zero
static void ZerosMap_PopIt_Zero(struct AppClassContext *fsm)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : ZerosMap_PopIt)\n");
    }
    EXIT_STATE(getState(fsm));
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: ZerosMap_&ZerosMap_PopIt.Zero()\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : ZerosMap_&ZerosMap_PopIt.Zero()\n");
    }
    popState(fsm);
    AppClassContext_OK(fsm);
}

const struct AppClassState ZerosMap_PopIt = { POPULATE_STATE(ZerosMap_PopIt), 1, "ZerosMap_PopIt" };

#define OnesMap_PushIt_C AppClassState_C
#define OnesMap_PushIt_EOS AppClassState_EOS
#define OnesMap_PushIt_Error AppClassState_Error
#define OnesMap_PushIt_OK AppClassState_OK
#define OnesMap_PushIt_One AppClassState_One
#define OnesMap_PushIt_Unknown AppClassState_Unknown
#define OnesMap_PushIt_Zero AppClassState_Zero
#define OnesMap_PushIt_Default AppClassState_Default
#define OnesMap_PushIt_Entry NULL
#define OnesMap_PushIt_Exit NULL
#define OnesMap_PopIt_C AppClassState_C
#define OnesMap_PopIt_EOS AppClassState_EOS
#define OnesMap_PopIt_Error AppClassState_Error
#define OnesMap_PopIt_OK AppClassState_OK
#define OnesMap_PopIt_One AppClassState_One
#define OnesMap_PopIt_Unknown AppClassState_Unknown
#define OnesMap_PopIt_Zero AppClassState_Zero
#define OnesMap_PopIt_Default AppClassState_Default
#define OnesMap_PopIt_Entry NULL
#define OnesMap_PopIt_Exit NULL
#define OnesMap_DefaultState_C AppClassState_C
#define OnesMap_DefaultState_EOS AppClassState_EOS
#define OnesMap_DefaultState_Error AppClassState_Error
#define OnesMap_DefaultState_OK AppClassState_OK
#define OnesMap_DefaultState_One AppClassState_One
#define OnesMap_DefaultState_Unknown AppClassState_Unknown
#define OnesMap_DefaultState_Zero AppClassState_Zero

#undef OnesMap_PushIt_EOS
#define OnesMap_PushIt_EOS OnesMap_DefaultState_EOS
#undef OnesMap_PopIt_EOS
#define OnesMap_PopIt_EOS OnesMap_DefaultState_EOS
#undef OnesMap_DefaultState_EOS
static void OnesMap_DefaultState_EOS(struct AppClassContext *fsm)
{
    struct AppClass* ctxt = getOwner(fsm);

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : OnesMap_DefaultState)\n");
    }
    EXIT_STATE(getState(fsm));
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: OnesMap_&OnesMap_DefaultState.EOS()\n");
    }
    clearState(fsm);
    emptyStateStack(fsm);
    AppClass_Unacceptable(ctxt);
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : OnesMap_&OnesMap_DefaultState.EOS()\n");
    }
    setState(fsm, &StartMap_Unacceptable);
    ENTRY_STATE(getState(fsm));
}

#undef OnesMap_PushIt_Unknown
#define OnesMap_PushIt_Unknown OnesMap_DefaultState_Unknown
#undef OnesMap_PopIt_Unknown
#define OnesMap_PopIt_Unknown OnesMap_DefaultState_Unknown
#undef OnesMap_DefaultState_Unknown
static void OnesMap_DefaultState_Unknown(struct AppClassContext *fsm)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : OnesMap_DefaultState)\n");
    }
    EXIT_STATE(getState(fsm));
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: OnesMap_&OnesMap_DefaultState.Unknown()\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : OnesMap_&OnesMap_DefaultState.Unknown()\n");
    }
    setState(fsm, &StartMap_Unacceptable);
    ENTRY_STATE(getState(fsm));
}

#undef OnesMap_PushIt_C
static void OnesMap_PushIt_C(struct AppClassContext *fsm)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : OnesMap_PushIt)\n");
    }
    EXIT_STATE(getState(fsm));
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: OnesMap_&OnesMap_PushIt.C()\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : OnesMap_&OnesMap_PushIt.C()\n");
    }
    setState(fsm, &OnesMap_PopIt);
    ENTRY_STATE(getState(fsm));
}

#undef OnesMap_PushIt_Error
static void OnesMap_PushIt_Error(struct AppClassContext *fsm)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : OnesMap_PushIt)\n");
    }
    EXIT_STATE(getState(fsm));
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: OnesMap_&OnesMap_PushIt.Error()\n");
    }
    clearState(fsm);
    emptyStateStack(fsm);
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : OnesMap_&OnesMap_PushIt.Error()\n");
    }
    setState(fsm, &StartMap_Unacceptable);
    ENTRY_STATE(getState(fsm));
}

#undef OnesMap_PushIt_OK
static void OnesMap_PushIt_OK(struct AppClassContext *fsm)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : OnesMap_PushIt)\n");
    }
    EXIT_STATE(getState(fsm));
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: OnesMap_&OnesMap_PushIt.OK()\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : OnesMap_&OnesMap_PushIt.OK()\n");
    }
    setState(fsm, &OnesMap_PopIt);
    ENTRY_STATE(getState(fsm));
}

#undef OnesMap_PushIt_One
static void OnesMap_PushIt_One(struct AppClassContext *fsm)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : OnesMap_PushIt)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: OnesMap_&OnesMap_PushIt.One()\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : OnesMap_&OnesMap_PushIt.One()\n");
    }
    pushState(fsm, &OnesMap_PushIt);
    ENTRY_STATE(getState(fsm));
}

#undef OnesMap_PushIt_Zero
static void OnesMap_PushIt_Zero(struct AppClassContext *fsm)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : OnesMap_PushIt)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: OnesMap_&OnesMap_PushIt.Zero()\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : OnesMap_&OnesMap_PushIt.Zero()\n");
    }
    pushState(fsm, &ZerosMap_PushIt);
    ENTRY_STATE(getState(fsm));
}

const struct AppClassState OnesMap_PushIt = { POPULATE_STATE(OnesMap_PushIt), 0, "OnesMap_PushIt" };

#undef OnesMap_PopIt_Default
static void OnesMap_PopIt_Default(struct AppClassContext *fsm)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : OnesMap_PopIt)\n");
    }
    EXIT_STATE(getState(fsm));
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: OnesMap_&OnesMap_PopIt.Default()\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : OnesMap_&OnesMap_PopIt.Default()\n");
    }
    popState(fsm);
    AppClassContext_Error(fsm);
}

#undef OnesMap_PopIt_One
static void OnesMap_PopIt_One(struct AppClassContext *fsm)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : OnesMap_PopIt)\n");
    }
    EXIT_STATE(getState(fsm));
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: OnesMap_&OnesMap_PopIt.One()\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : OnesMap_&OnesMap_PopIt.One()\n");
    }
    popState(fsm);
    AppClassContext_OK(fsm);
}

const struct AppClassState OnesMap_PopIt = { POPULATE_STATE(OnesMap_PopIt), 1, "OnesMap_PopIt" };

/*
 * Local variables:
 *  buffer-read-only: t
 * End:
 */
